repos:
  - repo: 'https://github.com/ambv/black'
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3
        types:
          - python
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: end-of-file-fixer
        exclude: ^tests/data/
      - id: requirements-txt-fixer
      - id: debug-statements
  - repo: 'https://github.com/pre-commit/pygrep-hooks'
    rev: v1.9.0
    hooks:
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations
  - repo: 'https://github.com/asottile/reorder_python_imports'
    rev: v3.8.1
    hooks:
      - id: reorder-python-imports
  - repo: 'https://github.com/Lucas-C/pre-commit-hooks-safety'
    rev: v1.3.0
    hooks:
      - id: python-safety-dependencies-check
  - repo: 'https://gitlab.com/pycqa/flake8'
    rev: '3.9.2'
    hooks:
      - id: flake8
