version: "3"

services:
  db-src-set-public-schema-full: &db
    image: autodesk/postgres-pglogical-docker:17
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /tmp/pgdata
    restart: on-failure
    networks:
      datacenter:
        ipv4_address: 10.5.0.5
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  db-dst-set-public-schema-full:
    <<: *db
    networks:
      datacenter:
        ipv4_address: 10.5.0.6

  db-src-set-non-public-schema-full:
    <<: *db
    networks:
      datacenter:
        ipv4_address: 10.5.0.7

  db-dst-set-non-public-schema-full:
    <<: *db
    networks:
      datacenter:
        ipv4_address: 10.5.0.8

  db-src-set-public-schema-exodus:
    <<: *db
    networks:
      datacenter:
        ipv4_address: 10.5.0.9

  db-dst-set-public-schema-exodus:
    <<: *db
    networks:
      datacenter:
        ipv4_address: 10.5.0.10

  db-src-set-non-public-schema-exodus:
    <<: *db
    networks:
      datacenter:
        ipv4_address: 10.5.0.11

  db-dst-set-non-public-schema-exodus:
    <<: *db
    networks:
      datacenter:
        ipv4_address: 10.5.0.12

  flake8:
    image: autodesk/pgbelt:latest
    command: poetry run flake8
    networks:
      - datacenter

  black:
    image: autodesk/pgbelt:latest
    command: poetry run black .
    networks:
      - datacenter

  tests:
    image: autodesk/pgbelt:latest
    environment:
      PUBLIC_FULL_SRC_IP: 10.5.0.5
      PUBLIC_FULL_DST_IP: 10.5.0.6
      NONPUBLIC_FULL_SRC_IP: 10.5.0.7
      NONPUBLIC_FULL_DST_IP: 10.5.0.8
      PUBLIC_EXODUS_SRC_IP: 10.5.0.9
      PUBLIC_EXODUS_DST_IP: 10.5.0.10
      NONPUBLIC_EXODUS_SRC_IP: 10.5.0.11
      NONPUBLIC_EXODUS_DST_IP: 10.5.0.12
    command: poetry run pytest --cov=pgbelt tests/
    depends_on:
      db-src-set-public-schema-full:
        condition: service_healthy
      db-dst-set-public-schema-full:
        condition: service_healthy
      db-src-set-non-public-schema-full:
        condition: service_healthy
      db-dst-set-non-public-schema-full:
        condition: service_healthy
      db-src-set-public-schema-exodus:
        condition: service_healthy
      db-dst-set-public-schema-exodus:
        condition: service_healthy
      db-src-set-non-public-schema-exodus:
        condition: service_healthy
      db-dst-set-non-public-schema-exodus:
        condition: service_healthy
    networks:
      - datacenter

  localtest:
    image: autodesk/pgbelt:latest
    environment:
      PUBLIC_FULL_SRC_IP: 10.5.0.5
      PUBLIC_FULL_DST_IP: 10.5.0.6
      NONPUBLIC_FULL_SRC_IP: 10.5.0.7
      NONPUBLIC_FULL_DST_IP: 10.5.0.8
      PUBLIC_EXODUS_SRC_IP: 10.5.0.9
      PUBLIC_EXODUS_DST_IP: 10.5.0.10
      NONPUBLIC_EXODUS_SRC_IP: 10.5.0.11
      NONPUBLIC_EXODUS_DST_IP: 10.5.0.12
    command: bash -c "cd /pgbelt-volume/ && poetry run python3 tests/integration/conftest.py --non-public-schema && pip3 install -e . && bash"
    depends_on:
      db-src-set-public-schema-full:
        condition: service_healthy
      db-dst-set-public-schema-full:
        condition: service_healthy
      db-src-set-non-public-schema-full:
        condition: service_healthy
      db-dst-set-non-public-schema-full:
        condition: service_healthy
      db-src-set-public-schema-exodus:
        condition: service_healthy
      db-dst-set-public-schema-exodus:
        condition: service_healthy
      db-src-set-non-public-schema-exodus:
        condition: service_healthy
      db-dst-set-non-public-schema-exodus:
        condition: service_healthy
    networks:
      - datacenter
    volumes:
      - ./:/pgbelt-volume/:rw

networks:
  datacenter:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
