version: "3"

services:
  db-src:
    image: autodesk/postgres-pglogical-docker:13
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /tmp/pgdata
    restart: on-failure
    networks:
      datacenter:
        ipv4_address: 10.5.0.5
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  db-dst:
    image: autodesk/postgres-pglogical-docker:13
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /tmp/pgdata
    restart: on-failure
    networks:
      datacenter:
        ipv4_address: 10.5.0.6
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  flake8:
    image: autodesk/pgbelt:latest
    command: poetry run flake8
    networks:
      - datacenter

  black:
    image: autodesk/pgbelt:latest
    command: poetry run black .
    networks:
      - datacenter

  tests:
    image: autodesk/pgbelt:latest
    environment:
      TEST_PG_SRC_HOST: localhost
      TEST_PG_SRC_IP: 10.5.0.5
      TEST_PG_SRC_DB: src
      TEST_PG_SRC_PORT: 5432
      TEST_PG_SRC_ROOT_USERNAME: postgres
      TEST_PG_SRC_ROOT_PASSWORD: postgres
      TEST_PG_DST_HOST: localhost
      TEST_PG_DST_IP: 10.5.0.6
      TEST_PG_DST_DB: dst
      TEST_PG_DST_PORT: 5432
      TEST_PG_DST_ROOT_USERNAME: postgres
      TEST_PG_DST_ROOT_PASSWORD: postgres
    command: poetry run pytest --cov=pgbelt tests/
    depends_on:
      db-src:
        condition: service_healthy
      db-dst:
        condition: service_healthy
    networks:
      - datacenter

  localtest:
    image: autodesk/pgbelt:latest
    environment:
      TEST_PG_SRC_HOST: localhost
      TEST_PG_SRC_IP: 10.5.0.5
      TEST_PG_SRC_DB: src
      TEST_PG_SRC_PORT: 5432
      TEST_PG_SRC_ROOT_USERNAME: postgres
      TEST_PG_SRC_ROOT_PASSWORD: postgres
      TEST_PG_DST_HOST: localhost
      TEST_PG_DST_IP: 10.5.0.6
      TEST_PG_DST_DB: dst
      TEST_PG_DST_PORT: 5432
      TEST_PG_DST_ROOT_USERNAME: postgres
      TEST_PG_DST_ROOT_PASSWORD: postgres
    command: bash -c "cd /pgbelt-volume/ && poetry run python3 tests/integration/conftest.py && pip3 install -e . && bash"
    depends_on:
      db-src:
        condition: service_healthy
      db-dst:
        condition: service_healthy
    networks:
      - datacenter
    volumes:
      - ./:/pgbelt-volume/:rw

networks:
  datacenter:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
