PYTHON_CODE_PATH="./dbupgrade"

.DEFAULT_GOAL := help

# This help function will automatically generate help/usage text for any make target that is commented with "##".
# Targets with a singe "#" description do not show up in the help text
help:
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-40s\033[0m %s\n", $$1, $$2}'

install: ## Install whatever you have locally
	pip install -e .

setup: ## Install development requirements. You should be in a virtualenv
	pip install -r requirements.txt && pip install -r requirements-test.txt && pre-commit install

test: ## Run tests
	pytest

tests: test

usage-doc:
	pip install -r requirements-docs.txt && typer pgbelt.main utils docs --name belt --output docs/usage.md

docs: usage-doc setup ## Rebuild any docs that can be autogenerated.
