version: "3.8"
services:
  db1:
    image: postgres:latest
    container_name: postgres_db1
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: db1
    volumes:
      - db1_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - pgnetwork

  db2:
    image: postgres:latest
    container_name: postgres_db2
    environment:
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password2
      POSTGRES_DB: db2
    volumes:
      - db2_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    networks:
      - pgnetwork

networks:
  pgnetwork:

volumes:
  db1_data:
  db2_data:
