name: 'Coverage Badge'

on:
  push:
    branches:
      - main
jobs:
  pgbelt_ci:
    name: Coverage Badge
    runs-on: ubuntu-latest
    steps:
      - name: Coverage Badge
        uses: tj-actions/coverage-badge-py@v1.8
      - name: Verify Changed Coverage Badge
        uses: tj-actions/verify-changed-files@v10
        id: changed_files
        with:
          files: coverage.svg
      - name: Commit files
        if: steps.changed_files.outputs.files_changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add coverage.svg
          git commit -m "ci: updated coverage.svg"
      - name: Push changes
        if: steps.changed_files.outputs.files_changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.github_token }}
          branch: ${{ github.ref }}
